make click_button by value work for image inputs and button tags
libwww-perl/WWW-Mechanize pull request #311
Opened 2020-10-03 18:34 UTC by simbabque

I would really like to make this change for `->click_button( number => $n )` as well, but I am sure that will break people's code. Extra buttons suddenly messing up the numbering is a no-go I think. So I went with just adding a comment about it instead.

Fixes #131

2020-10-03 21:28 UTC, oalders requested changes
Thanks! Looks great. I think a line ending needs to be cleaned up in order for the tests to pass.

2020-10-03 21:29 UTC, oalders commented on t/local/click_button.t
> +        unlike( $mech->uri, qr/Go/, 'Submit button was not transmited' );
s/transmited/transmitted/

2020-10-03 21:58 UTC, simbabque commented
Sorry about the whitespace and thanks for the review. I have now found the "trim trailing whitespace" setting in my new IDE. Force-pushing a new version in a few minutes.

2020-10-04 02:54 UTC, oalders approved these changes

2020-10-04 02:54 UTC, merged