Resubmit GH #14
libwww-perl/WWW-Mechanize pull request #334
Opened 2022-07-18 22:36 UTC by simbabque

I've rebased #14, tested and added a workflow job to run a regression test. Happy to discuss if we really need it, or if this is such an unusual edge case that it makes no sense to run this every time.

This closes #14 and fixes #221.

2022-07-18 23:40 UTC, oalders requested changes
Overall it looks good, but I think there are some disabled jobs that need to be re-enabled?

2022-07-18 23:40 UTC, oalders commented on .github/workflows/build-and-test.yml
> +  #         CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
Why is the coverage job disabled?

2022-07-18 23:40 UTC, oalders commented on .github/workflows/build-and-test.yml
>        - uses: actions/download-artifact@master
This should probably use `@v3`

2022-07-18 23:40 UTC, oalders commented on .github/workflows/build-and-test.yml
> +  #         - "5.34"
Could add 5.36 here.

2022-07-18 23:40 UTC, oalders commented on .github/workflows/build-and-test.yml
> +  #     - uses: actions/download-artifact@master
These should both probably use `@v3`

2022-07-18 23:40 UTC, oalders commented on .github/workflows/build-and-test.yml
> +  #         - "5.34"
Could add 5.36 here.

2022-07-18 23:40 UTC, oalders commented on .github/workflows/build-and-test.yml
> +  #     - uses: actions/download-artifact@master
This should probably use `@v3`

2022-07-19 06:25 UTC, simbabque commented
> Overall it looks good, but I think there are some disabled jobs that need to be re-enabled?

Oh no. That must have been the heat. I re-enabled them, and force-pushed but forgot to add the file first. Sorry about that. It's up to date now and building.

I'm going to bump the other suggestions in a separate PR.

2022-07-19 15:11 UTC, oalders approved these changes
🎊

2022-07-19 15:11 UTC, merged